version: '3.8'
services:
  strapi:
    build:
      context: ./AlcolabsStrapi
    image: alcolabsstrapi 
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "1337:1337"
    depends_on:
      - postgres

  express:
    build: ./APIREST
    environment:
      STRAPI_URL: http://strapi:1337/api
      NODE_ENV: ${NODE_ENV}
    ports:
      - "4000:4000"
    depends_on:
      - strapi

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
